export const COUNTRY_EMOJIS: Record<string, string> = {
  // North America & Caribbean
  Canada: "🇨🇦🍁🫎",
  "United States": "🇺🇸🗽🦅",
  Mexico: "🇲🇽💀🦋🌮",
  Guatemala: "🇬🇹🌋🦜",
  Belize: "🇧🇿🐠🐢",
  Honduras: "🇭🇳🦜🏝️",
  "El Salvador": "🇸🇻🌋🫓",
  Nicaragua: "🇳🇮🌋🐒",
  "Costa Rica": "🇨🇷🦥🐸🌳",
  Panama: "🇵🇦🚢🦜",
  Bahamas: "🇧🇸🏝️🐬",
  Cuba: "🇨🇺🎺🚗",
  Haiti: "🇭🇹🥁🎨",
  "Dominican Republic": "🇩🇴💃🐳",
  Jamaica: "🇯🇲🎶🏝️",
  "Trinidad and Tobago": "🇹🇹🥁🌈",
  Barbados: "🇧🇧🐢🏄",
  "Saint Lucia": "🇱🇨⛰️🛶",
  Grenada: "🇬🇩🌶️🌴",
  "Antigua and Barbuda": "🇦🇬⛵🏖️",
  Dominica: "🇩🇲🌋🌧️",
  "Saint Kitts and Nevis": "🇰🇳🚂⛰️",
  "Saint Vincent and the Grenadines": "🇻🇨🏝️⛵",

  // Europe
  Albania: "🇦🇱🦅⛰️",
  Andorra: "🇦🇩⛷️🏔️",
  Austria: "🇦🇹🎻🏔️",
  Belarus: "🇧🇾🌲🦬",
  Belgium: "🇧🇪🍫🧇",
  "Bosnia and Herzegovina": "🇧🇦🌉🏞️",
  Bulgaria: "🇧🇬🌹🐻",
  Croatia: "🇭🇷🏖️🏰",
  Cyprus: "🇨🇾🏛️🐢",
  "Czech Republic": "🇨🇿🕰️🏰",
  Denmark: "🇩🇰🧱🧜",
  Estonia: "🇪🇪🎶🌲",
  Finland: "🇫🇮🎅🦌❄️",
  France: "🇫🇷🗼🥐",
  Germany: "🇩🇪🧙‍♂️🏰",
  Greece: "🇬🇷🏛️🌊⚡",
  Hungary: "🇭🇺♨️🧩",
  Iceland: "🇮🇸🌋❄️🧝",
  Ireland: "🇮🇪☘️🌈",
  Italy: "🇮🇹🍕🏛️",
  Kosovo: "🇽🇰⛰️🎨",
  Latvia: "🇱🇻🌲💐",
  Liechtenstein: "🇱🇮🏰🏔️",
  Lithuania: "🇱🇹🌊🌾",
  Luxembourg: "🇱🇺🏰💃",
  Malta: "🇲🇹🏛️🎆",
  Moldova: "🇲🇩🍇🏰",
  Monaco: "🇲🇨🏎️⛵",
  Montenegro: "🇲🇪🏔️🌊",
  Netherlands: "🇳🇱🌷🚲",
  "North Macedonia": "🇲🇰🏞️🏰",
  Norway: "🇳🇴🛶🗻🌌",
  Poland: "🇵🇱🐉🦬",
  Portugal: "🇵🇹⛵🥧",
  Romania: "🇷🇴🧛🐻",
  "San Marino": "🇸🇲🏰🏹",
  Serbia: "🇷🇸⚡🎺",
  Slovakia: "🇸🇰🏰⛰️",
  Slovenia: "🇸🇮🏞️🐻",
  Spain: "🇪🇸💃🍅🏰",
  Sweden: "🇸🇪🌸🎮",
  Switzerland: "🇨🇭⛰️🍫",
  Ukraine: "🇺🇦🌻🥟",
  "United Kingdom": "🇬🇧🧙‍♂️☕🏰",
  "Vatican City": "🇻🇦⛪🎨",

  // Asia
  Afghanistan: "🇦🇫⛰️🕌",
  Armenia: "🇦🇲⛰️⛪",
  Azerbaijan: "🇦🇿🔥🏔️",
  Bahrain: "🇧🇭🏝️🏎️",
  Bangladesh: "🇧🇩🌾🛶",
  Bhutan: "🇧🇹⛰️🕯️",
  Brunei: "🇧🇳🌴🕌",
  Cambodia: "🇰🇭🏛️🕉️",
  China: "🇨🇳🐉🏯",
  Georgia: "🇬🇪⛰️🍇",
  India: "🇮🇳🪔🐅",
  Indonesia: "🇮🇩🌋🐉",
  Iran: "🇮🇷🕌🏜️",
  Iraq: "🇮🇶🏛️🛶",
  Israel: "🇮🇱🕍🌊",
  Japan: "🇯🇵🗻🎎",
  Jordan: "🇯🇴🏜️🏰",
  Kazakhstan: "🇰🇿🐎🌾",
  Kyrgyzstan: "🇰🇬⛰️🐎",
  Laos: "🇱🇦🌿🛕",
  Lebanon: "🇱🇧🌲🏛️",
  Malaysia: "🇲🇾🌴🏙️",
  Maldives: "🇲🇻🏝️🐠",
  Mongolia: "🇲🇳🏕️🐎",
  Myanmar: "🇲🇲🛕🐘",
  Nepal: "🇳🇵⛰️🙏",
  "North Korea": "🇰🇵⛰️🏯",
  "South Korea": "🇰🇷🎮🌃",
  Oman: "🇴🇲🏜️🏰",
  Pakistan: "🇵🇰🏔️🏏",
  Philippines: "🇵🇭🏝️🐠",
  Qatar: "🇶🇦🏟️🏜️",
  Russia: "🇷🇺❄️🐻",
  "Saudi Arabia": "🇸🇦🏜️🕋",
  Singapore: "🇸🇬🌉🏙️",
  "Sri Lanka": "🇱🇰🐘🏝️",
  Syria: "🇸🇾🏛️🌄",
  Taiwan: "🇹🇼🏙️🗻",
  Tajikistan: "🇹🇯⛰️🏕️",
  Thailand: "🇹🇭🏖️🐘",
  Turkmenistan: "🇹🇲🏜️🏛️",
  "United Arab Emirates": "🇦🇪🏙️🐪",
  Uzbekistan: "🇺🇿🏛️🌟",
  Vietnam: "🇻🇳🌾🛶",
  Yemen: "🇾🇪🏜️🏰",

  // Oceania
  Australia: "🇦🇺🦘🐨",
  "New Zealand": "🇳🇿🥝⛰️",

  // South America
  Argentina: "🇦🇷💃🐧",
  Bolivia: "🇧🇴🏜️🦩",
  Brazil: "🇧🇷🎉🌳",
  Chile: "🇨🇱🌋🐧",
  Colombia: "🇨🇴🌸🎺",
  Ecuador: "🇪🇨🐢🌋",
  Guyana: "🇬🇾💦🦜",
  Paraguay: "🇵🇾🕸️🦫",
  Peru: "🇵🇪🏔️🦙",
  Suriname: "🇸🇷🌧️🌳",
  Uruguay: "🇺🇾🌅🦁",
  Venezuela: "🇻🇪💧🦜",

  // Africa
  Algeria: "🇩🇿🏜️🏙️",
  Angola: "🇦🇴💦🦓",
  Benin: "🇧🇯🥁🕯️",
  Botswana: "🇧🇼🐘🌿",
  "Burkina Faso": "🇧🇫🎬🌾",
  Burundi: "🇧🇮🥁🌊",
  Cameroon: "🇨🇲🌳🦍",
  "Cape Verde": "🇨🇻🌊🎶",
  "Central African Republic": "🇨🇫🌳🐘",
  Chad: "🇹🇩🏜️🐫",
  Comoros: "🇰🇲🌋🏝️",
  Congo: "🇨🇬🌧️🦍",
  "Democratic Republic of Congo": "🇨🇩🌳🦍",
  Djibouti: "🇩🇯🏜️🌊",
  Egypt: "🇪🇬🏜️🏺",
  "Equatorial Guinea": "🇬🇶🌴🐒",
  Eritrea: "🇪🇷☕🌊",
  Eswatini: "🇸🇿⛰️🎭",
  Ethiopia: "🇪🇹⛰️☕",
  Gabon: "🇬🇦🌳🐘",
  Gambia: "🇬🇲🛶🐦",
  Ghana: "🇬🇭🧵🌴",
  Guinea: "🇬🇳🥁🏞️",
  "Guinea-Bissau": "🇬🇼🏝️🐬",
  Kenya: "🇰🇪🦒🦁",
  Lesotho: "🇱🇸⛰️🐎",
  Liberia: "🇱🇷🌊⚽",
  Libya: "🇱🇾🏜️🏛️",
  Madagascar: "🇲🇬🦎🌳",
  Malawi: "🇲🇼🏞️🐟",
  Mali: "🇲🇱🏜️📜",
  Mauritania: "🇲🇷🏜️🐪",
  Mauritius: "🇲🇺🏝️🐠",
  Morocco: "🇲🇦🕌🐪",
  Mozambique: "🇲🇿🏝️🐟",
  Namibia: "🇳🇦🏜️⭐",
  Niger: "🇳🇪🏜️🛶",
  Nigeria: "🇳🇬🎶🎥",
  Rwanda: "🇷🇼⛰️🦍",
  "Sao Tome and Principe": "🇸🇹🏝️🌴",
  Senegal: "🇸🇳🎵🏄",
  Seychelles: "🇸🇨🏝️🐢",
  "Sierra Leone": "🇸🇱🌊🌴",
  Somalia: "🇸🇴🌊🐪",
  "South Africa": "🇿🇦🦁🌈",
  "South Sudan": "🇸🇸🛶🦌",
  Sudan: "🇸🇩🏜️🏛️",
  Tanzania: "🇹🇿🦁⛰️",
  Togo: "🇹🇬🌴🎨",
  Tunisia: "🇹🇳🏛️🏜️",
  Uganda: "🇺🇬🦍⛵",
  "Western Sahara": "🇪🇭🏜️⭐",
  Zambia: "🇿🇲💧🐘",
  Zimbabwe: "🇿🇼💦🦏",
};
