"use client"
import "./globals.css"
import {UserAuthBuilderProvider} from '../../context/context';
import AuthStateWrapper from "@/components/Auth/AuthStateWrapper";
import PrimaryLayout from "@/layout/PrimaryLayout/PrimaryLayout";
import {createTheme, StyledEngineProvider, ThemeProvider} from "@mui/material/styles"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

import {
  primaryColor,
  secondaryColor,
  accentColor,
  helperTextColor,
  primaryFont,
  textColor,
  lightGrayColor
} from "@/helpers/variables/variables"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  palette: {
    primary: {
      main: primaryColor,
    },
    secondary: {
      main: secondaryColor,
    },
    info: {
      main: secondaryColor,
      contrastText: primaryColor
    },
    success: {
      main: textColor,
    }
  },
  typography: {
    fontFamily: primaryFont,
    allVariants: {
      textTransform: "capitalize"
    },
    h2: {
      fontSize: "1.5rem",
      fontWeight: 600,
      lineHeight: "2rem"
    },
    h3: {
      fontSize: "1.125rem"
    },
    body2: {
      color: helperTextColor
    },
  },
  components: {
    // MuiTextField: {
    //   styleOverrides: {
    //     root: {
    //       "& .MuiOutlinedInput-root": {
    //         borderRadius: '1rem',
    //         fontFamily: primaryFont,
    //         fontWeight: 400,
    //         textTransform: 'uppercase',
    //         color: textColor,
    //         '& fieldset': {
    //           border: '0.5px solid #B3B9BD',
    //         },
    //         '& input': {
    //           padding: '0.75rem 0.9rem'
    //         },
    //         '&::placeholder': {
    //           color: '#B3B9BD',
    //           fontSize: '0.875rem',
    //           fontFamily: 'primaryFont',
    //           fontWeight: 400,
    //           lineHeight: '150%'
    //         }
    //       },
    //       "& .MuiInputLabel-root": {
    //         textTransform: 'uppercase',
    //         fontWeight: 600,
    //         color: textColor,
    //         margin: "0 6px"
    //       },
    //       "& .MuiFormHelperText-root": {
    //         fontSize: "0.625rem",
    //         color: helperTextColor,
    //         position: 'relative',
    //         marginTop: "2px",
    //         zIndex: 1
    //       }
    //     }
    //   }
    // // },
    // MuiFormLabel: {
    //   styleOverrides: {
    //     asterisk: {
    //       color: accentColor
    //     }
    //   }
    // },
    // MuiOutlinedInput: {
    //   styleOverrides: {
    //     root: {
    //       borderRadius: 16
    //     },
    //     notchedOutline: {
    //       padding: "0 15px"
    //     }
    //   }
    // },
    // MuiSlider: {
    //   styleOverrides: {
    //     root: {
    //       color: primaryColor,
    //       height: 4,
    //       padding: '1rem 0',
    //       width: 'calc(50% - 1rem)',
    //       '& .MuiSlider-thumb': {
    //         width: '1rem',
    //         height: '1rem',
    //         marginRight: '0.5rem',
    //         marginLeft: '0.5rem'
    //       }
    //     }
    //   }
    // },
    MuiSelect: {
      styleOverrides: {
        select: {
          padding: '0.75rem 0.9rem'
        }
      }
    },
    MuiButton: {
      styleOverrides: {
        root: {
          padding: '15px 20px',
          borderRadius: 16,
          boxShadow: "none"
        },
        containedInfo: {
          '&:hover': {
            backgroundColor: secondaryColor,
            color: primaryColor,
          }
        }
      }
    },
    MuiSwitch: {
      styleOverrides: {
        root: {
          width: 42,
          height: 26,
          padding: 0
        },
        switchBase: {
          padding: 0,
          margin: 2,
          transitionDuration: '300ms',
          '&.Mui-checked': {
            transform: 'translateX(16px)',
            color: '#fff',
            '& + .MuiSwitch-track': {
              backgroundColor: primaryColor,
              opacity: 1,
              border: 0,
            },
            '&.Mui-disabled + .MuiSwitch-track': {
              opacity: 0.5,
            }
          },
          '&.Mui-focusVisible .MuiSwitch-thumb': {
            color: primaryColor,
            border: '6px solid #fff'
          },
          '&.Mui-disabled .MuiSwitch-thumb': {
            color: primaryColor
          },
          '&.Mui-disabled + .MuiSwitch-track': {
            opacity: 0.7
          },
        },
        thumb: {
          boxSizing: 'border-box',
          width: 22,
          height: 22
        },
        track: {
          borderRadius: 26 / 2,
          backgroundColor: '#B3B9BD',
          opacity: 1,
          transition: 'background-color 500ms'
        }
      }
    },
    MuiDivider: {
      styleOverrides: {
        root: {
          borderColor: lightGrayColor
        }
      }
    },
  }
})

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/icon?family=Material+Icons"
      />
    </head>
    <body>
    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
      <ThemeProvider theme={theme}>
        <UserAuthBuilderProvider>
          <AuthStateWrapper>
            <PrimaryLayout>
              {props.children}
            </PrimaryLayout>
          </AuthStateWrapper>
        </UserAuthBuilderProvider>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}


